### ========================================
### 1. REGISTER USER
### ========================================
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "password123",
  "fullName": "user1"
}

### ========================================
### 2. LOGIN
### ========================================
# @name Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "victor_final",
  "password": "password123"
}

### ========================================
### SET VARIABLE TOKEN
### ========================================
@token = {{Login.response.body.data.token}}

### ========================================
### 3. BUAT AKUN BANK
### ========================================
POST http://localhost:3000/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountName": "Tabungan Utama"
}

### ========================================
### 4. LIHAT DAFTAR AKUN
### ========================================
GET http://localhost:3000/accounts
Authorization: Bearer {{token}}

### ========================================
### 5. DEPOSIT
### ========================================
# Ganti accountId dengan ID asli dari response No. 4
POST http://localhost:3000/transactions/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": 1, 
  "amount": 500000
}

### ========================================
### 6. WITHDRAW
### ========================================
POST http://localhost:3000/transactions/withdraw
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountId": 1, 
  "amount": 50000
}

### ========================================
### 7. TRANSFER
### ========================================
# Pastikan 'toAccountNumber' valid dan beda akun
POST http://localhost:3000/transactions/transfer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fromAccountId": 1,
  "toAccountNumber": "NOMOR_REKENING_TUJUAN",
  "amount": 50000,
  "description": "Bayar hutang"
}

### ========================================
### 8. CEK HISTORY
### ========================================
GET http://localhost:3000/transactions/1
Authorization: Bearer {{token}}